version: "3.8"

services:
  chatbotapp:
    container_name: chatbot-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    # volumes:
    #   - .:/app
    networks:
      - chatbot
    restart: always
    
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - chatbot
    restart: always

networks:
  chatbot:
    external: true
      
