apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: chatbot
      containers:
        - name: backend-container
          image: 212945523191.dkr.ecr.ap-southeast-1.amazonaws.com/chatbot-app/backend:latest
          ports:
            - containerPort: 8000
          # envFrom:
          #   - secretRef:
          #       name: db-credentials-secret
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "backend-env"